#!/bin/bash
echo type in something
while read a
do
	temp=$a
done
f=$temp
c=`echo $f | tr 'a-z' 'A-Z'`
d=`echo $c | tr "()[]{}'" '@'`
d=`echo $d | tr '""' '@'`
d=`echo $d | tr '@' ' '`
d=`echo $d | tr ' ' '_'`
d=`echo $d | tr '. , : ? !' ' '`
echo $d > phrases.txt
d=`sed 's/ _/ /' phrases.txt`
for solo in $d
do
	echo $solo
done
