#!/bin/bash
echo type in something
while read a
do
	temp=$a
f=$temp
c=`echo $f | tr 'a-z' 'A-Z'`
d=`echo $c | tr "()[]{}'" '@'`
d=`echo $d | tr '""' '@'`
d=`echo $d | tr '@' ' '`
d=`echo $d | tr ' ' '_'`
d=`echo $d | tr '. , : ? !' ' '`
echo $d > phrases.txt
d=`sed 's/ _/ /' phrases.txt`
echo $d > phrases.txt
declare -A hash
for phrase in $d
do      
	count=${hash["$phrase"]}
	if [[ "$count" == "" ]]
		then
			count=1
                        while [[ i -le ${#hash[@]} ]]
				do
				i=0
			if [[ $phrase == ${hash[i]} ]]
					then
						count=$((count+1))
						echo "found <$count> instances"
				fi
				i=$((i+1))
		done
	fi
	echo "count = <$count>"
	echo $phrase
done
done
for key in ${!hash[@]}
	do
		echo key is $key
		echo value is ${hash[$key]}
done

